/*
 * Phoenix-RTOS
 *
 * POSIX.1-2017 standard library functions tests
 *
 * HEADER:
 *    - math.h
 *
 * TESTED:
 *    - accuracy of exp(), exp2(), expm1(), log(), log2(), log10(), log1p(),
 *      pow(), sqrt(), cbrt(), hypot(), sin(), cos(), tan(), asin(), acos(),
 *      atan(), atan2(), sinh(), cosh(), tanh(), asinh(), acosh(), atanh(),
 *      erf(), erfc(), lgamma(), tgamma(), fmod(), remainder() and their
 *      float variants, in ULPs from the correctly rounded result
 *    - the SHA-256 round constants as JavaScript crypto code derives them
 *      from pow()
 *
 * The reference values in accuracy-refs.h are correctly rounded (MPFR, 256
 * bits) and generated by the coordination repo's tools/libm-hosttest
 * (make gen-refs). The allowed distance is 1 ULP for the functions programs
 * treat as exact-ish (exp/log/pow/trig), 0 for the exact ones (sqrt, fmod,
 * remainder), 2-3 for the hyperbolic and gamma families; glibc is within all
 * of these.
 *
 * Copyright 2026 Phoenix Systems
 *
 * This file is part of Phoenix-RTOS.
 *
 * %LICENSE%
 */

#include <float.h>
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "common.h"
#include "accuracy-refs.h"
#include <unity_fixture.h>


TEST_GROUP(math_accuracy);


TEST_SETUP(math_accuracy)
{
}


TEST_TEAR_DOWN(math_accuracy)
{
}


/* Map a double onto a monotonically ordered integer, so that the distance in
 * ULPs between two finite values (or two equal infinities) is a subtraction. */
static int64_t acc_ordered(double x)
{
	int64_t i;

	memcpy(&i, &x, sizeof(i));
	return (i < 0) ? (INT64_MIN - i) : i;
}


static uint64_t acc_ulps(double got, double want)
{
	int64_t a, b;

	if (isnan(got) != 0) {
		return UINT64_MAX;
	}
	a = acc_ordered(got);
	b = acc_ordered(want);

	return (a > b) ? ((uint64_t)a - (uint64_t)b) : ((uint64_t)b - (uint64_t)a);
}


static uint64_t acc_ulpsf(float got, float want)
{
	int32_t a, b;

	if (isnan(got) != 0) {
		return UINT64_MAX;
	}
	memcpy(&a, &got, sizeof(a));
	memcpy(&b, &want, sizeof(b));
	a = (a < 0) ? (INT32_MIN - a) : a;
	b = (b < 0) ? (INT32_MIN - b) : b;

	return (a > b) ? (uint64_t)((int64_t)a - b) : (uint64_t)((int64_t)b - a);
}


static char acc_msg[192];


static void acc_check1(const char *name, double (*f)(double), const struct math_ref1 *t, size_t n, uint64_t ulps)
{
	size_t i, wi = 0;
	uint64_t d, worst = 0;

	for (i = 0; i < n; i++) {
		d = acc_ulps(f(t[i].x), t[i].r);
		if (d > worst) {
			worst = d;
			wi = i;
		}
	}
	if (worst > ulps) {
		snprintf(acc_msg, sizeof(acc_msg), "%s(%a) = %a, correctly rounded %a: %llu ULP > %llu",
			name, t[wi].x, f(t[wi].x), t[wi].r, (unsigned long long)worst, (unsigned long long)ulps);
		TEST_FAIL_MESSAGE(acc_msg);
	}
}


static void acc_check2(const char *name, double (*f)(double, double), const struct math_ref2 *t, size_t n, uint64_t ulps)
{
	size_t i, wi = 0;
	uint64_t d, worst = 0;

	for (i = 0; i < n; i++) {
		d = acc_ulps(f(t[i].x, t[i].y), t[i].r);
		if (d > worst) {
			worst = d;
			wi = i;
		}
	}
	if (worst > ulps) {
		snprintf(acc_msg, sizeof(acc_msg), "%s(%a, %a) = %a, correctly rounded %a: %llu ULP > %llu",
			name, t[wi].x, t[wi].y, f(t[wi].x, t[wi].y), t[wi].r, (unsigned long long)worst, (unsigned long long)ulps);
		TEST_FAIL_MESSAGE(acc_msg);
	}
}


static void acc_check1f(const char *name, float (*f)(float), const struct math_ref1 *t, size_t n, uint64_t ulps)
{
	size_t i, wi = 0;
	uint64_t d, worst = 0;

	for (i = 0; i < n; i++) {
		d = acc_ulpsf(f((float)t[i].x), (float)t[i].r);
		if (d > worst) {
			worst = d;
			wi = i;
		}
	}
	if (worst > ulps) {
		snprintf(acc_msg, sizeof(acc_msg), "%s(%a) = %a, correctly rounded %a: %llu ULP > %llu",
			name, t[wi].x, (double)f((float)t[wi].x), t[wi].r, (unsigned long long)worst, (unsigned long long)ulps);
		TEST_FAIL_MESSAGE(acc_msg);
	}
}


static void acc_check2f(const char *name, float (*f)(float, float), const struct math_ref2 *t, size_t n, uint64_t ulps)
{
	size_t i, wi = 0;
	uint64_t d, worst = 0;

	for (i = 0; i < n; i++) {
		d = acc_ulpsf(f((float)t[i].x, (float)t[i].y), (float)t[i].r);
		if (d > worst) {
			worst = d;
			wi = i;
		}
	}
	if (worst > ulps) {
		snprintf(acc_msg, sizeof(acc_msg), "%s(%a, %a) = %a, correctly rounded %a: %llu ULP > %llu",
			name, t[wi].x, t[wi].y, (double)f((float)t[wi].x, (float)t[wi].y), t[wi].r, (unsigned long long)worst, (unsigned long long)ulps);
		TEST_FAIL_MESSAGE(acc_msg);
	}
}


#define ACC_N(t) (sizeof(t) / sizeof((t)[0]))

/* fn and fnf against ref_fn / ref_fnf within REF_fn_ULPS / REF_fnF_ULPS */
#define ACC_TEST1(fn) \
	TEST(math_accuracy, fn) \
	{ \
		acc_check1(#fn, fn, ref_##fn, ACC_N(ref_##fn), REF_##fn##_ULPS); \
		acc_check1f(#fn "f", fn##f, ref_##fn##f, ACC_N(ref_##fn##f), REF_##fn##F_ULPS); \
	}

#define ACC_TEST2(fn) \
	TEST(math_accuracy, fn) \
	{ \
		acc_check2(#fn, fn, ref_##fn, ACC_N(ref_##fn), REF_##fn##_ULPS); \
		acc_check2f(#fn "f", fn##f, ref_##fn##f, ACC_N(ref_##fn##f), REF_##fn##F_ULPS); \
	}


ACC_TEST1(exp)
ACC_TEST1(exp2)
ACC_TEST1(expm1)
ACC_TEST1(log)
ACC_TEST1(log2)
ACC_TEST1(log10)
ACC_TEST1(log1p)
ACC_TEST2(pow)
ACC_TEST1(sqrt)
ACC_TEST1(cbrt)
ACC_TEST2(hypot)
ACC_TEST1(sin)
ACC_TEST1(cos)
ACC_TEST1(tan)
ACC_TEST1(asin)
ACC_TEST1(acos)
ACC_TEST1(atan)
ACC_TEST2(atan2)
ACC_TEST1(sinh)
ACC_TEST1(cosh)
ACC_TEST1(tanh)
ACC_TEST1(asinh)
ACC_TEST1(acosh)
ACC_TEST1(atanh)
ACC_TEST1(erf)
ACC_TEST1(erfc)
ACC_TEST1(lgamma)
ACC_TEST1(tgamma)
ACC_TEST2(fmod)
ACC_TEST2(remainder)


/* SHA-256 initial hash values H0..H7 and round constants K0..K63 (FIPS 180-4):
 * the first 32 bits of the fractional parts of the square roots of the first 8
 * primes and of the cube roots of the first 64 primes. */
static const uint32_t acc_sha256_h[8] = {
	0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19
};

static const uint32_t acc_sha256_k[64] = {
	0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
	0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
	0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
	0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
	0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
	0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
	0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
	0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2
};


/* sjcl (the Stanford JavaScript Crypto Library, JetStream's stanford-crypto-*)
 * computes these tables at startup as (x - Math.floor(x)) * 0x100000000 | 0
 * with x = Math.pow(prime, 1/2) or Math.pow(prime, 1/3): any pow() more than
 * about 2^-20 relative off the true root gives a wrong constant, i.e. a wrong
 * SHA-256. */
static uint32_t acc_frac32(double x)
{
	return (uint32_t)(int64_t)((x - floor(x)) * 4294967296.0);
}


TEST(math_accuracy, sha256_constants_from_pow)
{
	int primes[64], n = 0, c = 2, i;

	while (n < 64) {
		int prime = 1;
		for (i = 0; (i < n) && (primes[i] * primes[i] <= c); i++) {
			if ((c % primes[i]) == 0) {
				prime = 0;
				break;
			}
		}
		if (prime != 0) {
			primes[n++] = c;
		}
		c++;
	}

	for (i = 0; i < 8; i++) {
		snprintf(acc_msg, sizeof(acc_msg), "H%d = frac(pow(%d, 1/2))", i, primes[i]);
		TEST_ASSERT_EQUAL_HEX32_MESSAGE(acc_sha256_h[i], acc_frac32(pow(primes[i], 0.5)), acc_msg);
	}
	for (i = 0; i < 64; i++) {
		snprintf(acc_msg, sizeof(acc_msg), "K%d = frac(pow(%d, 1/3))", i, primes[i]);
		TEST_ASSERT_EQUAL_HEX32_MESSAGE(acc_sha256_k[i], acc_frac32(pow(primes[i], 1.0 / 3.0)), acc_msg);
	}
}


/* Exact results the old phoenix libm got wrong; volatile keeps the compiler
 * from evaluating anything at build time. */
TEST(math_accuracy, exact_results)
{
	volatile double m2 = -2.0, three = 3.0, seven = 7.0, one = 1.0, tiny = DBL_TRUE_MIN, big = 1e300, nzero = -0.0;
	volatile float m2f = -2.0f, threef = 3.0f;
	double ip;

	/* odd integer powers of a negative base are negative */
	TEST_ASSERT_EQUAL_DOUBLE(-8.0, pow(m2, three));
	TEST_ASSERT_EQUAL_DOUBLE(-0.125, pow(m2, -three));
	TEST_ASSERT_EQUAL_DOUBLE(-1.0, pow(-one, one));
	TEST_ASSERT_EQUAL_FLOAT(-8.0f, powf(m2f, threef));

	/* fmod is exact for any quotient size */
	TEST_ASSERT_DOUBLE_IS_ZERO(fmod(one, tiny));
	TEST_ASSERT_EQUAL_DOUBLE(1.0, fmod(big, seven)); /* the double 1e300 is 1 (mod 7) */

	/* the sign of a zero result */
	TEST_ASSERT_DOUBLE_IS_NEG_ZERO(ldexp(-0x1p-1000, -100));
	TEST_ASSERT_DOUBLE_IS_NEG_ZERO(modf(-0x1.265cb59f7172p+50, &ip));
	TEST_ASSERT_DOUBLE_IS_NEG_ZERO(remainder(nzero, one));
}


TEST_GROUP_RUNNER(math_accuracy)
{
	RUN_TEST_CASE(math_accuracy, exp);
	RUN_TEST_CASE(math_accuracy, exp2);
	RUN_TEST_CASE(math_accuracy, expm1);
	RUN_TEST_CASE(math_accuracy, log);
	RUN_TEST_CASE(math_accuracy, log2);
	RUN_TEST_CASE(math_accuracy, log10);
	RUN_TEST_CASE(math_accuracy, log1p);
	RUN_TEST_CASE(math_accuracy, pow);
	RUN_TEST_CASE(math_accuracy, sqrt);
	RUN_TEST_CASE(math_accuracy, cbrt);
	RUN_TEST_CASE(math_accuracy, hypot);
	RUN_TEST_CASE(math_accuracy, sin);
	RUN_TEST_CASE(math_accuracy, cos);
	RUN_TEST_CASE(math_accuracy, tan);
	RUN_TEST_CASE(math_accuracy, asin);
	RUN_TEST_CASE(math_accuracy, acos);
	RUN_TEST_CASE(math_accuracy, atan);
	RUN_TEST_CASE(math_accuracy, atan2);
	RUN_TEST_CASE(math_accuracy, sinh);
	RUN_TEST_CASE(math_accuracy, cosh);
	RUN_TEST_CASE(math_accuracy, tanh);
	RUN_TEST_CASE(math_accuracy, asinh);
	RUN_TEST_CASE(math_accuracy, acosh);
	RUN_TEST_CASE(math_accuracy, atanh);
	RUN_TEST_CASE(math_accuracy, erf);
	RUN_TEST_CASE(math_accuracy, erfc);
	RUN_TEST_CASE(math_accuracy, lgamma);
	RUN_TEST_CASE(math_accuracy, tgamma);
	RUN_TEST_CASE(math_accuracy, fmod);
	RUN_TEST_CASE(math_accuracy, remainder);
	RUN_TEST_CASE(math_accuracy, sha256_constants_from_pow);
	RUN_TEST_CASE(math_accuracy, exact_results);
}
