#
# Makefile for the kernel trace profiling tests
#
# Copyright 2026 Phoenix Systems
#
# %LICENSE%
#

NAME := test-prof-sampling
LOCAL_SRCS := test_prof_sampling.c
DEP_LIBS := unity

include $(binary.mk)
